#!/usr/bin/env python

import os

outfile_name='animcursor_tex.h'

build_list=['iconbusy', 'iconbusy.png']

tmpfile='.tmpfile'
build_list_str=' '.join(str(x) for x in build_list)
command='gdk-pixbuf-csource --build-list --raw '+build_list_str + ' > '+tmpfile
os.system(command)

with open(outfile_name,'wt') as out:
    for line in open(tmpfile):
        out.write(line.replace('guint8', 'unsigned char'))

os.remove (tmpfile)
